//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

let fib = [1, 2]
let fibSum = 0
function getSumOfSeries(limit){
  while(fib[fib.length-1] < (limit)){
    if(fib[fib.length-1] % 2 == 0 && fib[fib.length - 1] < limit){
      fibSum += fib[fib.length - 1]
    }
    fib.push(fib[fib.length-1] + fib[fib.length-2])
  }
}
getSumOfSeries(4000000)
console.log(fibSum)
